[build]
  # A base é a raiz mesmo
  base = "."
  
  # O site é gerado na pasta dist da raiz
  publish = "dist"
  
  # O comando roda direto na raiz
  command = "pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200